version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y maven curl wget
      - apt-get purge nodejs npm
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - apt-get install -y nodejs
      - node --version
  pre_build:
    commands:
      - pip install -U setuptools
      - pip install -r django-backend/requirements.txt
      - pip install  flake8 safety python-taint
      - safety check -r django-backend/requirements.txt
      - npm install -g @angular/cli
      - cd front-end && npm install && cd ..
      - cd front-end && ng build && cd ..
  build:
    commands:
  post_build:
    commands:
      - echo Build completed on `date`
