version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  api:
    build: './django-backend'
    image: fecnxg
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./django-backend:/opt/nxg_fec
    ports:
      - "8080:8080"
    depends_on:
      - db
  migration:
    image: fecnxg
    command: python manage.py migrate --noinput
    command: python manage.py loaddata fixtures/base_data.json
    volumes:
      - ./django-backend:/opt/nxg_fec
    depends_on:
      - db
  web:
    build: './front-end'
    restart: always
    volumes:
       - ./front-end/dist/fec-eFilling:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - api
      - migration
