version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5234:5234"
  web:
    build: .
    image: fecnxg
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./django-backend:/opt/nxg_fec
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migration
  migration:
    image: fecnxg
    command: python manage.py migrate --noinput
    volumes:
      - ./django-backend:/opt/nxg_fec
    depends_on:
      - db
