version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  api:
    env_file: ../local.env
    build: './django-backend'
    image: fecnxg
    volumes:
      - ./django-backend:/opt/nxg_fec
    ports:
      - "8080:8080"
    depends_on:
      - db
  web:
    build:
      context: './front-end'
      dockerfile: Dockerfile-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
